services:
  - type: web
    name: apiCars
    env: php
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://apicars-38aa.onrender.com
